const data = [
    {
      sku: "SKU001",
      name: "Product 1",
      price: 10.99,
      category: ["Category 1"],
      brand: "Brand 1",
      quantity: 5,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 1",
      date: "2023-06-01",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
      sku: "SKU002",
      name: "Product 2",
      price: 19.99,
      category: ["Category 2"],
      brand: "Brand 2",
      quantity: 8,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 2",
      date: "2023-06-02",
      desc: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
    {
      sku: "SKU003",
      name: "Product 3",
      price: 15.5,
      category: ["Category 1"],
      brand: "Brand 3",
      quantity: 3,
      variants: ["Variant 1"],
      supplier: "Supplier 3",
      date: "2023-06-03",
      desc: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    },
    {
      sku: "SKU004",
      name: "Product 4",
      price: 8.75,
      category: ["Category 3"],
      brand: "Brand 4",
      quantity: 12,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 4",
      date: "2023-06-04",
      desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.",
    },
    {
      sku: "SKU005",
      name: "Product 5",
      price: 12.99,
      category: ["Category 2"],
      brand: "Brand 5",
      quantity: 10,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 5",
      date: "2023-06-05",
      desc: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      sku: "SKU006",
      name: "Product 6",
      price: 6.49,
      category: ["Category 1"],
      brand: "Brand 1",
      quantity: 7,
      variants: ["Variant 1"],
      supplier: "Supplier 1",
      date: "2023-06-06",
      desc: "Nisi ut aliquip ex ea commodo consequat.",
    },
    {
      sku: "SKU007",
      name: "Product 7",
      price: 21.99,
      category: ["Category 3"],
      brand: "Brand 2",
      quantity: 15,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 2",
      date: "2023-06-07",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
    {
      sku: "SKU008",
      name: "Product 8",
      price: 14.5,
      category: ["Category 2"],
      brand: "Brand 3",
      quantity: 4,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 3",
      date: "2023-06-08",
      desc: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
      sku: "SKU009",
      name: "Product 9",
      price: 9.99,
      category: ["Category 1"],
      brand: "Brand 4",
      quantity: 9,
      variants: ["Variant 1"],
      supplier: "Supplier 4",
      date: "2023-06-09",
      desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    },
    {
      sku: "SKU010",
      name: "Product 10",
      price: 18.75,
      category: ["Category 3"],
      brand: "Brand 5",
      quantity: 6,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 5",
      date: "2023-06-10",
      desc: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      sku: "SKU011",
      name: "Product 11",
      price: 11.99,
      category: ["Category 2"],
      brand: "Brand 1",
      quantity: 11,
      variants: ["Variant 1"],
      supplier: "Supplier 1",
      date: "2023-06-11",
      desc: "Nisi ut aliquip ex ea commodo consequat.",
    },
    {
      sku: "SKU012",
      name: "Product 12",
      price: 25.99,
      category: ["Category 1"],
      brand: "Brand 2",
      quantity: 3,
      variants: ["Variant 1", "Variant 2", "Variant 3"],
      supplier: "Supplier 2",
      date: "2023-06-12",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
    {
      sku: "SKU013",
      name: "Product 13",
      price: 16.5,
      category: ["Category 3"],
      brand: "Brand 3",
      quantity: 8,
      variants: ["Variant 1", "Variant 2"],
      supplier: "Supplier 3",
      date: "2023-06-13",
      desc: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
      sku: "SKU014",
      name: "Product 14",
      price: 8.99,
      category: ["Category 2"],
      brand: "Brand 4",
      quantity: 5,
      variants: ["Variant 1", "Variant 2", "Variant 3", "Variant 4"],
      supplier: "Supplier 4",
      date: "2023-06-14",
      desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    },
    {
      sku: "SKU015",
      name: "Product 15",
      price: 19.75,
      category: ["Category 1"],
      brand: "Brand 5",
      quantity: 10,
      variants: ["Variant 1"],
      supplier: "Supplier 5",
      date: "2023-06-15",
      desc: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
  ];
  
  export default data;
  